server:
  port: 8089

spring:
  application:
    name: order-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: "http://localhost:8762/eureka,http://localhost:8761/eureka"
