logging:
  level:
    com.dayue: debug
    org.springframework: info

spring:
  #datasource
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exercisegroup?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  #rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #全局消息确认消费默认
    #listener.simple.acknowledge-mode: auto

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
