spring:
  jpa:
    show-sql: true
multi:
  datasource:
    one:
      url: jdbc:mysql://106.12.115.49:3307/exercisegroup?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
    two:
      url: jdbc:mysql://106.12.115.49:3308/exercisegroup?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*'